#!/usr/bin/env python

# Copyright (c) 2013 Sven Over <sven@svenover.de>
# Licensed under the MIT license, see the LICENSE file for details

import optparse
import os

def main():
    parser = optparse.OptionParser()
    parser.add_option("--source",
                      dest="source",
                      metavar='URL',
                      default='http://archive.raspbian.org/raspbian/',
                      help='raspbian source URL',
                      )
    options, args = parser.parse_args()

    if args:
        parser.print_usage()
        raise SystemExit(1)

    os.mkdir('local-repository')
    os.mkdir('local-repository/conf')

    open('local-repository/conf/distributions', 'w').write("""\
Codename: wheezy
Suite: testing
Origin: Raspbian
Architectures: armhf
Components: main
Contents: . .gz allcomponents
Update: raspbian
""")

    open('local-repository/conf/updates', 'w').write("""\
Name: raspbian
Method: {0}
FilterList: deinstall raspbian.packages
FilterSrcList: deinstall /dev/null
""".format(options.source))

    open('local-repository/conf/raspbian.packages', 'w')

if __name__ == '__main__':
    main()
